fix: Downgrade polars to 0.15.17 (#72)
### Checklist:

- [x] My pull request represents one logical piece of work
- [x] The commit message follows [conventional
commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] My code follows the recommendations in
[conventions](https://github.com/OrcaBaseHQ/conventions)

**What kind of change does this PR introduce?**
- Pin `polars` version to 0.15.17 in `pyproject.toml`

**Where should the reviewer start / focus on?**
- `pyproject.toml` 

#### Issue:
The `run_forecast_flow` returns `ValueError: setting an array element
with a sequence.` when it was run using lambda function. The polars
version `0.16.15` (indexhub) seems to caused one of the function
(`_make_y_lag` in functime) to return `List[List[i8]]` instead of
`List[i8]`

#### Fix: 
Downgrade polars to 0.15.17 would resolve the issue.

#### Output: 

![image](https://user-images.githubusercontent.com/82559807/219257382-00bb32f2-bdd7-44d8-bf12-a31b0d805082.png)

#### Expected output: 

![image](https://user-images.githubusercontent.com/82559807/219257593-07dfe4b0-8774-495a-9474-51175fbebc8a.png)

<details>
  <summary>Traceback / error message</summary>
  
02:35:01.033 | ERROR | Task run 'run_backtest-0' - Encountered exception
during execution:
TypeError: only size-1 arrays can be converted to Python scalars

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/task/prefect/engine.py", line 1511, in orchestrate_task_run
    result = await run_sync(task.fn, *args, **kwargs)
File "/var/task/prefect/utilities/asyncutils.py", line 156, in
run_sync_in_interruptible_worker_thread
    tg.start_soon(
  File "/var/task/anyio/_backends/_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "/var/task/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
File "/var/task/anyio/_backends/_asyncio.py", line 937, in
run_sync_in_worker_thread
    return await future
  File "/var/task/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
File "/var/task/prefect/utilities/asyncutils.py", line 135, in
capture_worker_thread_and_result
    result = __fn(*args, **kwargs)
File "/var/task/indexhub/flows/forecasting.py", line 349, in
run_backtest
    y_pred = _fit_and_predict(
File "/var/task/indexhub/flows/forecasting.py", line 230, in
_fit_and_predict
    y_pred = zero_inflated_model(
  File "/var/task/functime/base/forecaster.py", line 48, in __call__
    return self.predict(fh=fh, freq=freq, X=X_future)
  File "/var/task/functime/base/forecaster.py", line 126, in predict
    y_pred_vals = __predict(state, **pred_kwargs)
File "/var/task/functime/forecasting/_ar.py", line 481, in
predict_autoreg
    y_pred = predict_recursive(**predict_kwargs)
File "/var/task/functime/forecasting/_ar.py", line 394, in
predict_recursive
    y_pred_i = regressor.predict(X=x_arr)
  File "/var/task/functime/forecasting/censored.py", line 57, in predict
    weights = self.classify(X)
  File "/var/task/lightgbm/sklearn.py", line 997, in predict_proba
result = super().predict(X, raw_score, start_iteration, num_iteration,
pred_leaf, pred_contrib, **kwargs)
  File "/var/task/lightgbm/sklearn.py", line 797, in predict
    X = _LGBMCheckArray(X, accept_sparse=True, force_all_finite=False)
  File "/var/task/sklearn/utils/validation.py", line 879, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
File "/var/task/sklearn/utils/_array_api.py", line 185, in
_asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
ValueError: setting an array element with a sequence.
02:35:01.060 | ERROR | Task run 'run_backtest-0' - Finished in state
Failed('Task run encountered an exception: TypeError: only size-1 arrays
can be converted to Python scalars\n\nThe above exception was the direct
cause of the following exception:\n\nValueError: setting an array
element with a sequence.\n')
02:35:01.062 | ERROR | Flow run 'vivacious-unicorn' - Encountered
exception during execution:
TypeError: only size-1 arrays can be converted to Python scalars

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/task/prefect/engine.py", line 650, in orchestrate_flow_run
    result = await run_sync(flow_call)
File "/var/task/prefect/utilities/asyncutils.py", line 156, in
run_sync_in_interruptible_worker_thread
    tg.start_soon(
  File "/var/task/anyio/_backends/_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "/var/task/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
File "/var/task/anyio/_backends/_asyncio.py", line 937, in
run_sync_in_worker_thread
    return await future
  File "/var/task/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
File "/var/task/prefect/utilities/asyncutils.py", line 135, in
capture_worker_thread_and_result
    result = __fn(*args, **kwargs)
File "/var/task/indexhub/flows/forecasting.py", line 674, in
run_forecast_flow
    run_backtest(
  File "/var/task/prefect/tasks.py", line 456, in __call__
    return enter_task_run_engine(
  File "/var/task/prefect/engine.py", line 940, in enter_task_run_engine
    return run_async_from_worker_thread(begin_run)
File "/var/task/prefect/utilities/asyncutils.py", line 177, in
run_async_from_worker_thread
    return anyio.from_thread.run(call)
  File "/var/task/anyio/from_thread.py", line 49, in run
    return asynclib.run_async_from_thread(func, *args)
File "/var/task/anyio/_backends/_asyncio.py", line 970, in
run_async_from_thread
    return f.result()
File "/var/lang/lib/python3.9/concurrent/futures/_base.py", line 446, in
result
    return self.__get_result()
File "/var/lang/lib/python3.9/concurrent/futures/_base.py", line 391, in
__get_result
    raise self._exception
File "/var/task/prefect/engine.py", line 1089, in
get_task_call_return_value
    return await future._result()
  File "/var/task/prefect/futures.py", line 237, in _result
return await final_state.result(raise_on_failure=raise_on_failure,
fetch=True)
  File "/var/task/prefect/states.py", line 89, in _get_state_result
    raise await get_state_exception(state)
  File "/var/task/prefect/engine.py", line 1511, in orchestrate_task_run
    result = await run_sync(task.fn, *args, **kwargs)
File "/var/task/prefect/utilities/asyncutils.py", line 156, in
run_sync_in_interruptible_worker_thread
    tg.start_soon(
  File "/var/task/anyio/_backends/_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "/var/task/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
File "/var/task/anyio/_backends/_asyncio.py", line 937, in
run_sync_in_worker_thread
    return await future
  File "/var/task/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
File "/var/task/prefect/utilities/asyncutils.py", line 135, in
capture_worker_thread_and_result
    result = __fn(*args, **kwargs)
File "/var/task/indexhub/flows/forecasting.py", line 349, in
run_backtest
    y_pred = _fit_and_predict(
File "/var/task/indexhub/flows/forecasting.py", line 230, in
_fit_and_predict
    y_pred = zero_inflated_model(
  File "/var/task/functime/base/forecaster.py", line 48, in __call__
    return self.predict(fh=fh, freq=freq, X=X_future)
  File "/var/task/functime/base/forecaster.py", line 126, in predict
    y_pred_vals = __predict(state, **pred_kwargs)
File "/var/task/functime/forecasting/_ar.py", line 481, in
predict_autoreg
    y_pred = predict_recursive(**predict_kwargs)
File "/var/task/functime/forecasting/_ar.py", line 394, in
predict_recursive
    y_pred_i = regressor.predict(X=x_arr)
  File "/var/task/functime/forecasting/censored.py", line 57, in predict
    weights = self.classify(X)
  File "/var/task/lightgbm/sklearn.py", line 997, in predict_proba
result = super().predict(X, raw_score, start_iteration, num_iteration,
pred_leaf, pred_contrib, **kwargs)
  File "/var/task/lightgbm/sklearn.py", line 797, in predict
    X = _LGBMCheckArray(X, accept_sparse=True, force_all_finite=False)
  File "/var/task/sklearn/utils/validation.py", line 879, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
File "/var/task/sklearn/utils/_array_api.py", line 185, in
_asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
ValueError: setting an array element with a sequence.
02:35:01.089 | ERROR | Flow run 'vivacious-unicorn' - Finished in state
Failed('Flow run encountered an exception. TypeError: only size-1 arrays
can be converted to Python scalars\n\nThe above exception was the direct
cause of the following exception:\n\nValueError: setting an array
element with a sequence.\n')
File "/var/task/prefect/utilities/asyncutils.py", line 156, in
run_sync_in_interruptible_worker_thr File
"/var/task/prefect/utilities/asyncutils.py", line 156, in
run_sync_in_interruptible_worker_thr result = super().predict(X,
raw_score, start_iteration, num_iteration, pred_leaf, pred_contrib, *
array = numpy.asarray(array, order=order, dtype=dtype)in
_asarray_with_order
END RequestId: 22714d18-5b2f-4a1a-a807-9c11c1cb446a
REPORT RequestId: 22714d18-5b2f-4a1a-a807-9c11c1cb446a Init Duration:
0.10 ms Duration: 11605.98 msBilled Duration: 11606 ms Memory Size: 3008
MB Max Memory Used: 3008 MB
</details>

**Is this tested? If not, any recommendations for how to test this, or
anything you are worried about?**
Yes tested with tourism data

Note:
Related issue/PR in polars github
- https://github.com/pola-rs/polars/issues/6913. 
- https://github.com/pola-rs/polars/pull/6487.